### ISSUE TITLE
nonce is too short.

### ISSUE THREAD

**Issue by skylinezum** [you21979/node-poloniex#3]
nonce should be 16 digit or poloniex will return an error.

**Comment by you21979** [comment]
> The nonce parameter is an integer which must always be greater than the previous nonce used.

There remains a value that has been used in a previous program to apikey of polo.
Create a new key or Customize the nance value.

```
var api = poloniex.createPrivateApi(config.APIKEY, config.SECRET, "");
api.nonce += (1 * 1e15)
```

**Comment by you21979** [comment]
Private API must be accessed sequentially.
- error pattern:scream:

```
var api = poloniex.createPrivateApi(config.APIKEY, config.SECRET, "")
api.marginAccountSummary().then(function(res){
    console.log(res)
})
api.marginAccountSummary().then(function(res){
    console.log(res)
})
```
- success pattern:yum:

```
var api = poloniex.createPrivateApi(config.APIKEY, config.SECRET, "")
api.marginAccountSummary().then(function(res){
    console.log(res)
    return api.marginAccountSummary().then(function(res){
        console.log(res)
    })
})
```

Please be mastering the promise.

**Comment by you21979** [comment]
https://gist.github.com/you21979/e845a045a04c5c582aee46703bed5b37
sample bot

**Comment by skylinezum** [comment]
Thanks,

I didn't notice that nonce was part of the prototype.
